spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kirandb
    username: MYSYSTEM
    password: system
  jpa:
    show-sql: true
    generate-ddl: false
